INSERT INTO stablishments (id, name, created_at, updated_at, deleted_at) VALUES (1, 'HOSPITAL CLINICO MAGALLANES', NOW(), NULL, NULL);
INSERT INTO stablishments (id, name, created_at, updated_at, deleted_at) VALUES (2, 'HOSPITAL DR. AUGUSTO ESSMANN BURGOS', NOW(), NULL, NULL);
INSERT INTO stablishments (id, name, created_at, updated_at, deleted_at) VALUES (3, 'HOSPITAL DE PORVENIR', NOW(), NULL, NULL);
INSERT INTO stablishments (id, name, created_at, updated_at, deleted_at) VALUES (4, 'HOSPITAL COMUNITARIO CRISTINA CALDERÓN', NOW(), NULL, NULL);
INSERT INTO stablishments (id, name, created_at, updated_at, deleted_at) VALUES (5, 'COSAM MIRAFLORES', NOW(), NULL, NULL);
INSERT INTO stablishments (id, name, created_at, updated_at, deleted_at) VALUES (6, 'SERVICIO DE SALUD MAGALLANES', NOW(), NULL, NULL);
INSERT INTO users (id, first_name, second_name, first_last_name, second_last_name, email, username, password, rut, created_at, updated_at, deleted_at) VALUES (1, 'Usuario', 'Virtual', 'Sistema', '', 'virtual@redsalud.gob.cl', 'virtual', 'dummy-password', ' ', NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1001', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '10591000', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'ULTRACONGELADOR -80º', 'HAIER', 'DW-86L490J', 'BE0FS4G1T00QGP3B0002', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1002', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '10591000', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'ULTRACONGELADOR -80º', 'HAIER', 'DW-86L490J', 'BE0FS4G1T00QGP4T0002', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1003', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '4141200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'VITRINA REFRIGIRADA', 'HAIER', 'HYC-509', 'BE0HS1E1T00QJP2P0005', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1004', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '4141200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'VITRINA REFRIGIRADA', 'HAIER', 'HYC-509', 'BE0HS1E1T00QJN4K0019', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1005', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '392462', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROCENTRIFUGA', 'DLAB', 'DM0424', 'HB212AX0001436', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1006', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '392462', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROCENTRIFUGA', 'DLAB', 'DM0424', 'HB212AX0001437', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1007', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '392462', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROCENTRIFUGA', 'DLAB', 'DM0424', 'HB223BC0001848', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1008', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '392462', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROCENTRIFUGA', 'DLAB', 'DM0424', 'HB21BBB0001710', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1009', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1782620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782653', '2023-08-31 00:00:00', '7699062', ' ', ' ', ' ', 'CENTRIFUGA TIPO SPIN', 'DLAB', 'DM1008', 'IA234AM0000622', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1010', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1782620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782653', '2023-08-31 00:00:00', '7699062', ' ', ' ', ' ', 'CENTRIFUGA TIPO SPIN', 'DLAB', 'DM1008', 'IA234AM0000623', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1011', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1782620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782653', '2023-08-31 00:00:00', '7699062', ' ', ' ', ' ', 'CENTRIFUGA TIPO SPIN', 'DLAB', 'DM1008', 'IA234AM0000624', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1012', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1782620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782653', '2023-08-31 00:00:00', '7699062', ' ', ' ', ' ', 'CENTRIFUGA TIPO SPIN', 'DLAB', 'DM1008', 'IA234AM0000625', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1013', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '284291', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782653', '2023-08-31 00:00:00', '7699062', ' ', ' ', ' ', 'VORTEX', 'DLAB', 'MX-S', 'VB22CAS00087780', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1014', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '284291', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782653', '2023-08-31 00:00:00', '7699062', ' ', ' ', ' ', 'VORTEX', 'DLAB', 'MX-S', 'VB22CAS00087777', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1015', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1999200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROPIPETA MULTICANAL ELECTRONICAS', 'EPPENDORF', 'XPLORER', 'K31454L', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1016', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1999200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROPIPETA MULTICANAL ELECTRONICAS', 'EPPENDORF', 'XPLORER', 'K31469L', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1017', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1999200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROPIPETA MULTICANAL ELECTRONICAS', 'EPPENDORF', 'XPLORER', 'K31459L', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1018', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '797062', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'JUEGO MICROPIPETAS ELECTRONICAS (3)', 'EPPENDORF', 'RESEARCH PLUS', 'GD228AS0000080-GD227AQ0001983-GD22BAW0002258', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1019', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '797062', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'JUEGO MICROPIPETAS ELECTRONICAS (3)', 'EPPENDORF', 'RESEARCH PLUS', 'GD228AS0000081-GD227AQ0001985-GD22BAW0002259', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1020', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1338631', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROPIPETA ELECTRONICA MONOCANAL', 'EPPENDORF', 'XPLORER', 'R23593L', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1021', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '12', '2024-04-15 00:00:00', '1180730-22-SE23', '1338631', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782652', '2023-08-31 00:00:00', '41303234', ' ', ' ', ' ', 'MICROPIPETA ELECTRONICA MONOCANAL', 'EPPENDORF', 'XPLORER', 'R23533L', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1022', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '10591000', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'ULTRACONGELADOR -80º', 'HAIER', 'DW-86L490J', 'BEDFS4G1T00QGP3B0004', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1023', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '4141200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'VITRINA REFRIGIRADA', 'HAIER', 'HYC-509', 'BEQHS1E1T00QJP2P0006', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1024', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '392462', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'MICROCENTRIFUGA', 'DLAB', 'DM0424', 'IA234AM0000620', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1025', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '392462', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'MICROCENTRIFUGA', 'DLAB', 'DM0424', 'IA234AM0000621', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1026', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '1782620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'CENTRIFUGA TIPO SPIN', 'DLAB', 'DM1008', 'HB223BC0001861', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1027', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '1782620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'CENTRIFUGA TIPO SPIN', 'DLAB', 'DM1008', 'HB223BC0001852', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1028', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '284291', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'VORTEX', 'DLAB', 'MX-S', 'VB22CAS0007799', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1029', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '797062', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'JUEGO MICROPIPETAS ELECTRONICAS', 'EPPENDORF', 'RESEARCH PLUS', 'GD22BAW0002260-GD228AS0000082-GD227AQ0002008', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1030', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '1999200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'MICROPIPETA MULTICANAL ELECTRONICAS', 'EPPENDORF', 'XPLORER', 'E98902624406', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1031', '2024-04-24 00:00:00', '64', 'REPOSICION Y ADQUISICION EQUIPOS MEDICOS COVID RED ASISTENCIAL MAGALLANES', 'FNDR', '13', '2024-04-15 00:00:00', '1180730-22-SE23', '1999200', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', '782655', '2023-08-31 00:00:00', '20312586', ' ', ' ', ' ', 'MICROPIPETA MULTICANAL ELECTRONICAS', 'EPPENDORF', 'XPLORER', 'E98902624349', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1032', '2024-06-29 00:00:00', '95', 'REPOSICION Y ADQUISICION DE SELLADORAS PARA LA CENTRAL DE ESTERILIZACION HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '18', '2024-06-18 00:00:00', '1180730-5-SE24', '5835748', 'MEGALABS CHILE SA', '94544000-7', ' ', ' ', ' ', '844367', '2024-06-13 00:00:00', ' ', 'SELLADORA CON IMPRESORA', 'WIPAK', 'RS300', '30220996', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1033', '2024-06-29 00:00:00', '95', 'REPOSICION Y ADQUISICION DE SELLADORAS PARA LA CENTRAL DE ESTERILIZACION HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '18', '2024-06-18 00:00:00', '1180730-5-SE24', '5835748', 'MEGALABS CHILE SA', '94544000-7', ' ', ' ', ' ', '844367', '2024-06-13 00:00:00', ' ', 'SELLADORA CON IMPRESORA', 'WIPAK', 'RS300', '30220997', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1034', '2024-06-29 00:00:00', '95', 'REPOSICION Y ADQUISICION DE SELLADORAS PARA LA CENTRAL DE ESTERILIZACION HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '18', '2024-06-18 00:00:00', '1180730-5-SE24', '12886510', 'MEGALABS CHILE SA', '94544000-7', ' ', ' ', ' ', '841528', '2024-04-24 00:00:00', ' ', 'SELLADORA CON ENSOBRADORA', 'WIPAK', 'PMM-V 100-240', '3207551', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1035', '2024-06-29 00:00:00', '95', 'REPOSICION Y ADQUISICION DE SELLADORAS PARA LA CENTRAL DE ESTERILIZACION HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '18', '2024-06-18 00:00:00', '1180730-5-SE24', '12886510', 'MEGALABS CHILE SA', '94544000-7', ' ', ' ', ' ', '841528', '2024-04-24 00:00:00', ' ', 'SELLADORA CON ENSOBRADORA', 'WIPAK', 'PMM-V 100-240', '3207553', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1036', '2024-07-23 00:00:00', ' ', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '21', '2024-07-17 00:00:00', '1180730-6-SE24', '18408167', 'GEMCO GENERAL MACHINERY S.A', '76142730-K', ' ', ' ', ' ', '25343', '2024-06-21 00:00:00', '55224501', 'SILLON DENTAL', 'FLIGHT DENTAL', 'A6', 'A6A6S23111249', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1037', '2024-07-23 00:00:00', ' ', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '21', '2024-07-17 00:00:00', '1180730-6-SE24', '18408167', 'GEMCO GENERAL MACHINERY S.A', '76142730-K', ' ', ' ', ' ', '25343', '2024-06-21 00:00:00', '55224501', 'SILLON DENTAL', 'FLIGHT DENTAL', 'A6', 'A6A6S23111239', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1038', '2024-07-23 00:00:00', ' ', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '21', '2024-07-17 00:00:00', '1180730-6-SE24', '18408167', 'GEMCO GENERAL MACHINERY S.A', '76142730-K', ' ', ' ', ' ', '25343', '2024-06-21 00:00:00', '55224501', 'SILLON DENTAL', 'FLIGHT DENTAL', 'A6', 'A6A6S23111236', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1039', '2024-08-14 00:00:00', ' ', 'REPOSICION EQUIPOS PARA LA UNIDAD DE OFTALMOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '26', '2025-08-07 00:00:00', '1180730-12-SE24', '100315996', 'OFTOMED SA', '78075900-3', ' ', ' ', ' ', '78036', '2024-07-15 00:00:00', '100315996', 'FACOEMULSIFICADOR', 'JOHNSON & JOHNSON', 'VERITAS', '202310234', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1040', '2024-09-03 00:00:00', '130', 'REPOSICION Y ADQUISICION DE EQUIPOS PARA UNIDAD DE ALIMENTACION Y NUTRICION, HCM', 'FNDR', '32', '2024-08-19 00:00:00', '1180730-11-SE24', '1773100', 'COMERCIAL MAQUINET LIMITADA', '77534640-K', ' ', ' ', ' ', '56566', '2024-07-08 00:00:00', '3546200', 'BAÑO MARIA', 'MAQUIMET', 'BM 4D', '130', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1041', '2024-09-04 00:00:00', '122', 'REPOSICION Y ADQUISICION DE EQUIPOS PARA UNIDAD DE ALIMENTACION Y NUTRICION, HCM', 'FNDR', '33', '2024-08-01 00:00:00', '1180730-11-SE24', '5497800', 'COMERCIAL MAQUINET LIMITADA', '77534640-K', ' ', ' ', ' ', '56625', '2024-07-17 00:00:00', '5497800', 'MESON ARMADO DE BANDEJAS', 'MAQUIMET', 'MA-4', ' ', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1042', '2024-09-04 00:00:00', '130', 'REPOSICION Y ADQUISICION DE EQUIPOS PARA UNIDAD DE ALIMENTACION Y NUTRICION, HCM', 'FNDR', '32', '2024-08-19 00:00:00', '1180730-11-SE24', '1773100', 'COMERCIAL MAQUINET LIMITADA', '77534640-K', ' ', ' ', ' ', '56566', '2024-07-08 00:00:00', '3546200', 'BAÑO MARIA', 'MAQUIMET', 'BM 4D', '127', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1043', '2024-10-01 00:00:00', '150', 'REPOSICION EQUIPOS PARA LA UNIDAD DE OFTALMOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '34', '2024-09-27 00:00:00', '1180730-13-SE24', '55091050', 'ALCON LABORATORIOS CHILE LTDA', '86537600-6', ' ', ' ', ' ', ' ', ' ', ' ', 'LASER QUIRURGICO EXTERNO', 'ALCON', 'PUREPOINT', '2301892801X', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1044', '2024-10-11 00:00:00', ' ', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '39', '2024-10-10 00:00:00', '1180730-17-SE24', '6067810', 'PV EQUIP SA', '79895670-1', ' ', ' ', ' ', '116050', '2024-09-13 00:00:00', '6067810', 'ELECTROCARDIOGRAFO', 'GENERAL ELECTRIC', 'MAC 2000', 'STX23140120PA', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1045', '2024-11-25 00:00:00', '182', 'REPOSICION Y ADQUISICION EQUIPOS PARA UNIDAD DE OTORRINOLARINGOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '46', '2024-11-14 00:00:00', '1180730-22-SE24', '13694877', 'COMERCIALIZADORA CARLOS VALDIVIA SPA', '76422630-5', ' ', ' ', ' ', '38946', '2024-11-13 00:00:00', '68476908', 'AUDIOMETRO', 'INTERACOUSTICS', 'AC 40', 'SN1058557', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1046', '2024-11-25 00:00:00', '182', 'REPOSICION Y ADQUISICION EQUIPOS PARA UNIDAD DE OTORRINOLARINGOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '46', '2024-11-14 00:00:00', '1180730-22-SE24', '6614020', 'COMERCIALIZADORA CARLOS VALDIVIA SPA', '76422630-5', ' ', ' ', ' ', '38946', '2024-11-13 00:00:00', '68476908', 'IMPEDANCIOMETRO', 'INTERACOUSTICS', 'AT 235', 'SN1023287', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1047', '2024-11-25 00:00:00', '182', 'REPOSICION Y ADQUISICION EQUIPOS PARA UNIDAD DE OTORRINOLARINGOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '46', '2024-11-14 00:00:00', '1180730-22-SE24', '48168011', 'COMERCIALIZADORA CARLOS VALDIVIA SPA', '76422630-5', ' ', ' ', ' ', '38946', '2024-11-13 00:00:00', '68476908', 'VIDEONISTAGMOGRAFO', 'INTERACOUSTICS', 'VNG 525', 'SN3000510', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1048', '2024-11-25 00:00:00', ' ', 'REPOSICION Y ADQUISICION EQUIPOS PARA UNIDAD DE OTORRINOLARINGOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '40', '2024-11-13 00:00:00', '1180730-19-SE24', '5593000', 'COMERCIALIZADORA CARLOS VALDIVIA SPA', '76422630-5', ' ', ' ', ' ', '38552', '2024-10-03 00:00:00', '5593000', 'SILLON OTORRINO', 'EUROCLINIC', 'XENON EVO', 'CQ230008', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1049', '2024-12-04 00:00:00', ' ', 'REPOSICION Y ADQUISICION EQUIPOS PARA UNIDAD DE OTORRINOLARINGOLOGIA DEL HOSPITAL CLINICO DE MAGALLANES', 'FNDR', '49', '2024-12-04 00:00:00', '1180730-21-SE24', '15940233', 'GAES SA', '96848260-2', ' ', ' ', ' ', '576244', '2024-12-02 00:00:00', '15940233', 'VHIT (VIDEO HEAD IMPULSE TEST)', 'INTERACOUSTICS', 'EYESEECAM VHIT', 'SN1059392', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1050', '2025-05-08 00:00:00', ' ', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-22031043', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1051', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-22031057', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1052', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038392', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1053', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038397', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1054', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038399', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1055', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038406', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1056', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038409', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1057', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038410', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1058', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '7494620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR MULTIPARAMETRO MEDIANA COMPLEJIDAD', 'MINDRAY', 'ePM12M', 'AC9-2A038413', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1059', '2025-05-08 00:00:00', '67', 'REPOSICION EQUIPOS PARA EL HOSPITAL DR. AUGUSTO ESSMANN BURGOS DE PUERTO NATALES', 'FNDR', '33', '2025-03-27 00:00:00', '1180730-18-SE24', '12373620', 'IMPORTADORA Y DISTRIBUIDORA ARQUIMED LTDA', '92999000-5', ' ', ' ', ' ', '1055441', '2024-09-02 00:00:00', '79825200', 'MONITOR DESFIBRILADOR', 'MINDRAY', 'D6', 'DZ-2A019168', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1060', '2025-08-05 00:00:00', ' ', 'ADQUISICION EQUIPAMIENTO MAMOGRAFO MOVIL REGION DE MAGALLANES Y LA ANTARTICA CHILENA', 'FNDR', '27', '2024-07-31 00:00:00', '1180730-9-AG24', '151487', 'COMERCIAL E INDUSTRIAL MUEBLES ASENJO LIMITADA', '77018060-0', ' ', ' ', ' ', '8462', '2024-06-26 00:00:00', '802298', 'SILLA SALA ESPERA', 'TERA', 'TRINEO', ' ', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1061', '2025-08-05 00:00:00', ' ', 'ADQUISICION EQUIPAMIENTO MAMOGRAFO MOVIL REGION DE MAGALLANES Y LA ANTARTICA CHILENA', 'FNDR', '27', '2024-07-31 00:00:00', '1180730-9-AG24', '151487', 'COMERCIAL E INDUSTRIAL MUEBLES ASENJO LIMITADA', '77018060-0', ' ', ' ', ' ', '8462', '2024-06-26 00:00:00', '802298', 'SILLA SALA ESPERA', 'TERA', 'TRINEO', ' ', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1062', '2025-08-05 00:00:00', ' ', 'ADQUISICION EQUIPAMIENTO MAMOGRAFO MOVIL REGION DE MAGALLANES Y LA ANTARTICA CHILENA', 'FNDR', '27', '2024-07-31 00:00:00', '1180730-9-AG24', '249662', 'COMERCIAL E INDUSTRIAL MUEBLES ASENJO LIMITADA', '77018060-0', ' ', ' ', ' ', '8462', '2024-06-26 00:00:00', '802298', 'SILLA ERGONOMICA', 'Q3', 'BASE CROMADA', ' ', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1063', '2025-08-05 00:00:00', ' ', 'ADQUISICION EQUIPAMIENTO MAMOGRAFO MOVIL REGION DE MAGALLANES Y LA ANTARTICA CHILENA', 'FNDR', '27', '2024-07-31 00:00:00', '1180730-9-AG24', '249662', 'COMERCIAL E INDUSTRIAL MUEBLES ASENJO LIMITADA', '77018060-0', ' ', ' ', ' ', '8462', '2024-06-26 00:00:00', '802298', 'SILLA ERGONOMICA', 'Q3', 'BASE CROMADA', ' ', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1064', '2025-08-25 00:00:00', '135', 'ADQUISICION EQUIPOS PARA OPERATIVOS DE SALUD Y RONDAS MEDICAS RED ASISTENCIAL MAGALLANES', 'FNDR', '15', '2025-07-29 00:00:00', '1180730-12-SE25', '35462000', 'PLUSMEDICAL SPA', '76520087-3', ' ', ' ', ' ', '14375', '2025-07-11 00:00:00', '35462000', 'ECOTOMOGRAFO PORTATIL', 'VINNO', 'VINNO 10', 'U1662QN001', ' ', ' ', 6, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1065', '2025-09-24 00:00:00', '151', 'ADQUISICION EQUIPOS PARA OPERATIVOS DE SALUD Y RONDAS MEDICAS RED ASISTENCIAL MAGALLANES', 'FNDR', '35', '2025-09-10 00:00:00', '1180730-11-SE25', '12705999', 'ANDOVER ALIANZA MEDICA SA', '96625550-1', ' ', ' ', ' ', '73445', '2025-07-17 00:00:00', '38117997', 'SET TRANSDUCTORES ECOGRAFOS', 'PHILIPS', 'LUMIFY', 'F039HG', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1066', '2025-09-24 00:00:00', '151', 'ADQUISICION EQUIPOS PARA OPERATIVOS DE SALUD Y RONDAS MEDICAS RED ASISTENCIAL MAGALLANES', 'FNDR', '35', '2025-09-10 00:00:00', '1180730-11-SE25', '12705999', 'ANDOVER ALIANZA MEDICA SA', '96625550-1', ' ', ' ', ' ', '73445', '2025-07-17 00:00:00', '38117997', 'SET TRANSDUCTORES ECOGRAFOS', 'PHILIPS', 'LUMIFY', 'F0FF05', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);
INSERT INTO registers (n_inventary, date_reception, n_memo, project, financing, n_acta_reception, date_acta_reception, purchase_order, acquisition_value, provider, rut_provider, n_fact, date_fact, amount_fact, n_dispatch_guide, date_dispatch_guide, amount_dispatch_guide, description_property, brand, model, n_serie, n_res_info, date_res_info, stablishment_id, observation_state, n_res_gore, date_res_gore, n_res_accept, date_res_accept, state, user_id, created_at, updated_at, deleted_at)
VALUES ('1067', '2025-09-24 00:00:00', '151', 'ADQUISICION EQUIPOS PARA OPERATIVOS DE SALUD Y RONDAS MEDICAS RED ASISTENCIAL MAGALLANES', 'FNDR', '35', '2025-09-10 00:00:00', '1180730-11-SE25', '12705999', 'ANDOVER ALIANZA MEDICA SA', '96625550-1', ' ', ' ', ' ', '73445', '2025-07-17 00:00:00', '38117997', 'SET TRANSDUCTORES ECOGRAFOS', 'PHILIPS', 'LUMIFY', 'F0FG0H', ' ', ' ', 1, 'A LA ESPERA DE RESOLUCION DE TRANSFERENCIA DE DOMINIO POR PARTE DEL GORE', ' ', ' ', ' ', ' ', 'PENDIENTE', 1, NOW(), NULL, NULL);